var guestList = ["Zara", "Maham", "Minal"];
var dontCome = guestList[0];
console.log(dontCome, "nai aah skte hai");
guestList.splice(0, 1, "Mehak");
console.log("Good News!, we have found a bigger table for Dinner");
guestList.unshift("Usman");
guestList.push("Ali");
var middleIndex = Math.floor(guestList.length / 2);
guestList.splice(middleIndex, 0, "Ayesha");
console.log("Updated List of our guest");
guestList.forEach(function (guest) { return console.log("Salam ".concat(guest, ", Would you like to dinner with me?")); });
